version: '3.2'
services:
  iqgt-pdf-compile:
    image: ghcr.io/morimorijap/iqgt:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - ghcr.io/morimorijap/iqgt:latest
    volumes:
      - .:/workdir
